package designPattern.builder;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Builder.java
//  @ Date : 2016/5/20
//  @ Author : 
//
//




public class Builder {
	public void BuildPart() {
	
	}
}
