package designPattern.builder;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ConcreteBuilder.java
//  @ Date : 2016/5/20
//  @ Author : 
//
//




public class ConcreteBuilder extends Builder{
	
	private Product product;
	public void BuildPart() {
	
	}
	
	public void GetResult() {
	
	}
}
