package designPattern.builder;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Director.java
//  @ Date : 2016/5/20
//  @ Author : 
//
//




public class Director {
	public void Construct() {
	
	}
}
