package designPattern.builder;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Product.java
//  @ Date : 2016/5/20
//  @ Author : 
//
//

public class Product{
	public Part partA;
	public Part partB;
	public Part partC;
	public Part getPartA() {
		return partA;
	}
	public void setPartA(Part partA) {
		this.partA = partA;
	}
	public Part getPartB() {
		return partB;
	}
	public void setPartB(Part partB) {
		this.partB = partB;
	}
	public Part getPartC() {
		return partC;
	}
	public void setPartC(Part partC) {
		this.partC = partC;
	}
	
	
}

